### PR TITLE
ICKEPS and some assignments

### PR DESCRIPTION
**Pull request by haz**

### CODE REVIEW

**Comment by haz** [comment]
@maurovallati : What's the status of this fork? Things ready to merge in?

**Comment by maurovallati** [comment]
> @maurovallati : What's the status of this fork? Things ready to merge in?
Absolutely @haz I thought I did it already

**Comment by haz** [comment]
@jan-dolejsi Look ok to you?

**Comment by haz** [comment]
Hrmz...it actually looks like the commits were mirrored on the main branch?

https://github.com/AI-Planning/modeling-in-pddl/network

Trying to make sense of that network graph. I guess this PR isn't needed then?

**Pull request merged**
